### ISSUE TITLE
Can we help?

### ISSUE THREAD

**Issue by randycoulman** [configcat/elixir-sdk#1]
We (the e-commerce team at InfluxData) wrote a ConfigCat client for Elixir a few months ago.  It's currently embedded within our one of our (closed-source) apps, but I was literally just about to create a new repo to extract and open source our work when I found this repo.

I don't see any code here yet, but we're wondering how far along you are with development. Can we combine forces to make a single, official Elixir client for ConfigCat?

**Comment by laliconfigcat** [comment]
Hey,

I just created the repository, we don't have any code. We don't have any experiences with Elixir, but we could help you if you have any questions. It would be awesome if you could push your code so we could review and check it. I gave you write permissions for this repo.

**Comment by randycoulman** [comment]
Sounds good! It'll probably be a couple of days before I can get the code extracted and pushed up, but I will get it done.  We have a fully-functioning client that we've been running in production for a couple of months now; there's a few features missing that we didn't need, but we were planning to add some of those as part of our open-sourcing effort.

**Comment by laliconfigcat** [comment]
I'm deeply sorry, I missed the part that you are from the InfluxData team. 
Actually one of our other customers told us that they would help us in creating this SDK, and I thought they wrote to us here.

I'm glad that both of you could help us. Let's combine the forces and make a great official Elixir SDK!

I've created a elixir-sdk channel on our community slack channel. I think there we could talk about the details: 
https://join.slack.com/t/configcat-community/shared_invite/enQtMzkwNDg3MjQ3MTUyLWY1ZmE0NjY5NjA0YjAzMWU3MDg3ODhkMGI2ZjdmZjZmYTY4YTg1NmQ0YzBhMTVhOGE5YmNiYTI5OTg4NmNjYTQ

**Comment by igorescobar** [comment]
Hey guys! That's great!

We (Drover) were organizing ourselves to develop a new one based on the Ruby SDK. If you guys at InfluxData already have something already running on production would be could if we could start from where you guys are at the moment 👍

**Comment by igorescobar** [comment]
This is what we had planned:
<img width="800" alt="Screenshot 2020-10-15 at 09 42 07" src="https://user-images.githubusercontent.com/24032/96099039-b521b580-0eca-11eb-9339-9f065efa5d61.png">

Not sure how far you guys are at the moment. We based the work on the guidelines @laliconfigcat provided via e-mail a few days back.

**Comment by laliconfigcat** [comment]
I gave you write permissions too for this repo @igorescobar. 
Please send me who should I give write permissions from your sides.
