### ISSUE TITLE
Upgrade httpoison dependency

### ISSUE THREAD

**Issue by petemcfarlane** [configcat/elixir-sdk#138]
### Is your feature request related to a problem? Please describe.

Hi, I'm trying to install the configcat dependency to my Elixir project, but get the following error
```
Resolving Hex dependencies...
Resolution completed in 1.007s
Because your app depends on configcat ~> 4.0.0 which depends on httpoison ~> 1.7, httpoison ~> 1.7 is required.
So, because your app depends on httpoison ~> 2.1, version solving failed.
** (Mix) Hex dependency resolution failed
```

### Describe the solution you'd like

Is there a way we can make the dependency more flexible? for example `{:httpoison, "~> 1.7 or ~> 2.0"}`

### Describe alternatives you've considered

Forking this project?!

**Comment by kp-cat** [comment]
Hey @petemcfarlane,
Thanks for reaching out and for the suggestion. We have updated the `httpoison` dependency and will release it tomorrow.

**Comment by petemcfarlane** [comment]
Brilliant, thanks! 🤩
