### ISSUE TITLE
Update to config_v5.json format

### ISSUE THREAD

**Issue by randycoulman** [configcat/elixir-sdk#18]
We are using now the new config_v5.json format. There are some breaking changes in that (structure modified).

_Originally posted by @laliconfigcat in https://github.com/configcat/elixir-sdk/pull/2#discussion_r506365292_

**Comment by igorescobar** [comment]
@laliconfigcat could you give us some guidance on this one regarding on what to expect for this one?

**Comment by igorescobar** [comment]
Discussion: https://configcat-community.slack.com/archives/C01CN2YNWGK/p1603105539002700
