### ISSUE TITLE
Publicize the library

### ISSUE THREAD

**Issue by randycoulman** [configcat/elixir-sdk#22]
Announce the existence of the library in various ways:

Maybe some or all of:
- blog post
- submission to various Elixir newsletters
- Twitter
- ElixirForum post
- submit PR to https://github.com/h4cc/awesome-elixir

Having the SDK listed in the official docs will help a lot as well, but if we tell people about this SDK it might draw some more interest in ConfigCat as well.

**Comment by randycoulman** [comment]
Submitted to the awesome-Elixir list: https://github.com/h4cc/awesome-elixir/pull/4750

**Comment by laliconfigcat** [comment]
Awesome! Thanks!

**Comment by randycoulman** [comment]
Blog post: https://thenewstack.io/elixir-sdk-for-configcat/

I'll submit that to the newsletters shortly, which will then result in at least one tweet.

**Comment by randycoulman** [comment]
Submitted to Elixir Status (which resulted in a tweet and also provides content for Elixir Weekly) and Elixir Radar.

With that, I'll close this issue. We can do more publicity in the future if we want.
