### ISSUE TITLE
Add Dialyzer & Typespecs

### ISSUE THREAD

**Issue by randycoulman** [configcat/elixir-sdk#23]
Many Elixir projects rely on Dialyzer typespecs. As a library, we should provide proper type specs for our clients to rely on.  They also help document use of the library.

As I've been adding behaviours to the system, I've specified some typespecs. For now, I've hard-coded `map()` as the type of a config, but we will likely want to define a more explicit type for that and use it everywhere.

**Comment by igorescobar** [comment]
- [x] Dialyzer
- [x] Typespecs on the Public API
