### ISSUE TITLE
Improve public interface

### ISSUE THREAD

**Issue by igorescobar** [configcat/elixir-sdk#30]
The idea is to change the current public interface from:

```elixir
{:ok, client} = ConfigCat.start_link("sdk_key", fetch_policy: FetchPolicy.manual())
value = ConfigCat.get_value("any_feature", "default", client: client)
```

To:

```elixir
{:ok, client} = ConfigCat.create_client("sdk_key", fetch_policy: FetchPolicy.manual())
value = client.get_value("any_feature", "default")
```

This change would make our public interface more similar to the ones we currently have on other SDKs.

<img width="914" alt="Screenshot 2020-10-20 at 10 11 06" src="https://user-images.githubusercontent.com/24032/96565749-ad905100-12bc-11eb-915c-a6a3b7217661.png">

Previous discussion:
https://configcat-community.slack.com/archives/C01CN2YNWGK/p1603106388007500

**Comment by igorescobar** [comment]
@randycoulman It doesn't have to be "exactly" like that but if we manage to get rid of the `client: client` from the get_value interface would be already a nice improvement.

**Comment by randycoulman** [comment]
@igorescobar Based on our discussions on #37 and the PRs that resulted from that, can we consider this issue resolved now?
