### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by randycoulman** [configcat/elixir-sdk#4]
Add full documentation, including:

- [x] Fleshing out the README with more information about how to use the library and add it to a supervision tree
- [x] Documentation for the ConfigCat website
- [x] Adding module documentation for publishing to hexdocs.pm

**Comment by randycoulman** [comment]
From @laliconfigcat in https://github.com/configcat/elixir-sdk/pull/2#discussion_r506320497:

We'd like to use the same format for the readme.md as the other SDKs.

Getting started
Sample/Demo apps
Polling Modes
Need help?
Contributing
About ConfigCat

**Comment by igorescobar** [comment]
@laliconfigcat I was looking at the Ruby SDK Readme file and it mentions also the public documentation (on the Configcat website). How do you suggest us to deal with this?

**Comment by igorescobar** [comment]
Talking with @laliconfigcat over Slack he mentioned that the website docs are here:
https://github.com/configcat/docs

So we can also just send a PR there and then reference it here on the README.

**Comment by igorescobar** [comment]
I'm starting to work on the README.md draft

**Comment by igorescobar** [comment]
Working on the " Documentation for the ConfigCat website"
