### ISSUE TITLE
Getting a GenServer timeout when refreshing config

### ISSUE THREAD

**Issue by ischolten** [configcat/elixir-sdk#61]
### Describe the bug

Using the auto policy, we are often getting a GenServer timeout from the FetchConfig genserver. 

```elixir
{:timeout, {GenServer, :call, [ConfigCat.ConfigFetcher, :fetch, 5000]}}
```

In `CacheControlConfigFetcher`, the `handle_call` for `:fetch` is making a request and using the HTTPoison library which has some timeouts that are larger than the `GenServer.call/2` default time.

https://hexdocs.pm/elixir/GenServer.html#call/3
> call(server, request, timeout \\ 5000)

https://hexdocs.pm/httpoison/HTTPoison.Request.html
>:timeout - timeout for establishing a TCP or SSL connection, in milliseconds. Default is 8000
:recv_timeout - timeout for receiving an HTTP response from the socket. Default is 5000

### To reproduce

Run ConfigCat with the auto policy and  let it run, this will periodically happen.

### Expected behavior

The genserver allows enough time for the fetching of the updated config from ConfigCat or handles this error in some way.

**Comment by randycoulman** [comment]
I'll add here that sometimes a call to `ConfigCat.get_value` will timeout as well, because it gets blocked behind an in-progress fetch.
