### ISSUE TITLE
Failed tests on Elixir 1.11.x

### ISSUE THREAD

**Issue by kp-cat** [configcat/elixir-sdk#64]
### Describe the bug

13 tests are failed on Elixir 1.11.x. (All tests are working on Elixir 1.10.x)

### To reproduce
- Install Elixir 1.11.x dev environment
- Install dependencies
   ```bash
   mix local.rebar --force
   mix local.hex --force
   mix deps.get
   ```
- Run tests
   ```bash
   mix coveralls.json
   ```
- 13 tests are failed:
   ```bash 
   108 tests, 13 failures
   ```

### Expected behavior

All tests are passed on all Elixir versions

### SDK version

v1.0.1

### Language/Framework version

Erlang/OTP 23 [erts-11.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]
IEx 1.11.4 (compiled with Erlang/OTP 23)

### Platform
Mac OS X 10.15.7

**Comment by randycoulman** [comment]
It looks like the 1.11 tests are failing with an `unknown CA` SSL error when trying to pull the config from the ConfigCat servers. I'm not sure why yet, but I'll dig into it when I get a chance. My guess is some kind of mismatch between supported SSL versions between Erlang 23 and the SSL certs on the ConfigCat server.
