### ISSUE TITLE
Timeouts in GenServer calls leak to the calling application

### ISSUE THREAD

**Issue by randycoulman** [configcat/elixir-sdk#68]
### Describe the bug

Occasionally, a call to `ConfigCat.get_value` will time out. The timeout is not handled and therefore leaks to the calling application which can crash a process if the caller doesn't handle the timeout either.

```
Erlang error: {:timeout, {GenServer, :call, [ConfigCat.Client, {:get_value, "myFeatureFlag", false, nil}, 10000]}}
```

### To reproduce

It is not easy to reproduce this, as it only happens occasionally.

### Expected behavior

Any ConfigCat API call that has a default value should rescue the timeout error and return the default value rather than leaking the timeout back to the calling application. This includes `get_value` and `get_variation_id`.

It is less clear what should happen for calls like `get_all_keys`, `get_all_variation_ids`, and `get_key_and_value`, but probably returning empty lists for the first two and `nil` for the last would be best.

`force_refresh` should return `{:error, :timeout}` or similar.

My intention when I implemented this library is that `get_value` and similar calls shouldn't block on HTTP requests which is what seems to be happening here, so it would also be worth figuring out how these timeouts are happening in the first place to see if we can fix the root cause. I'll look into that as well.

**Comment by randycoulman** [comment]
In the latest instance of this issue, I see this sequence of events:

```
May 28 03:54:54 [info] Fetching configuration from ConfigCat
May 28 03:54:55 ** (stop) exited in: GenServer.call(ConfigCat.Client, {:get_value, "quartzHttpRetriesEnabled", false, nil}, 10000)
May 28 03:54:56 [info] ConfigCat configuration json fetch response code: 304 Cached: "60b036b7-14054"
```

So it looks like the fetch isn't the root cause of the timeout, as it started only 1 second before the timeout happened and completed in two seconds. By design, the fetch happens in a separate task.

It is possible that our app is making enough calls to `get_value` that it backs up the process's message queue. We'll look at that on our end.

**Comment by zoltan-david** [comment]
Hey Randy, is this issue still valid?

**Comment by randycoulman** [comment]
Yes, but it's pretty rare. I haven't had the bandwidth to dig in and fix it yet, sorry.

**Comment by kp-cat** [comment]
The Elixir SDK has been re-architecting since this issue was opened. We close this GitHub issue and see what happens with the new architecture. We can re-open later if the same issue arises again.
