### ISSUE TITLE
Publish package and documentation

### ISSUE THREAD

**Issue by randycoulman** [configcat/elixir-sdk#7]
Publish the library to hex.pm and the documentation to hexdocs.pm.

We'll have previously set up CI for building and testing (in #6) and written the documentation (in #4), but once we're ready to officially release this SDK, we'll want to start publishing to hex.pm and hexdocs.pm.

**Comment by igorescobar** [comment]
duplicated #4 #6

**Comment by randycoulman** [comment]
Re-opening with an updated description to more clearly specify the scope.

**Comment by randycoulman** [comment]
Here are the instructions for publishing to hex.pm and hexdocs.pm: https://hex.pm/docs/publish.

We'll want to add the package metadata to `mix.exs` and then @laliconfigcat, I think you'll need to take care of a few things on your end:

- Registering a hex user
- Generating a key to use for publishing: https://hexdocs.pm/hex/Mix.Tasks.Hex.User.html#module-generate-user-key
- Adding the key as the `HEX_API_KEY` env var in TravisCI

It's not well-documented, but it looks as though that will allow us to publish from CI.

Once we have that, we'll need to figure out how we want to trigger a release; we have to be sure to bump the version number before we release, so I don't think we want to publish on every commit to master.  Maybe we can set it up to trigger a release whenever a new tag is pushed?

I'm hoping you already have this figured out for the other SDKs and we can just follow whatever pattern is used there.

**Comment by laliconfigcat** [comment]
I registered at hex.pm, generated the api key and added it to Travis.
We only want to publish to the registry after github releases. 
We usually have a deploy.md in the root of the repo, which shows the steps. e.g.: https://github.com/configcat/ruby-sdk/blob/master/DEPLOY.md

So here the steps would be to increase the version number in the code then create a release in github with the corresponding version number.

**Comment by igorescobar** [comment]
Hey @laliconfigcat 👋 
So all we need to do is to create a new tag?

**Comment by laliconfigcat** [comment]
After some travis yml modification, you'll need to increase the version in the code and publish a release on github.
I didn't do anything with the travis yml, i just added the secret.

**Comment by igorescobar** [comment]
addressed on #59
